name: Build and test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  schedule:
    - cron: '0 10 15 * *'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        build_type: [ Debug, Release ]
        os: [ ubuntu-latest, macos-latest, windows-2019 ]
  
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        shell: bash
        run: |
          git clone https://guattari.tech/kit.git

      - name: Setup MSVC Env
        uses: TheMrMilchmann/setup-msvc-dev@v2.0.1

      - name: Build and test
        shell: bash
        working-directory: ${{ github.workspace }}/kit
        run: |
          sh build_and_test.sh || exit 1
